version: "3.8"
services:
    grafana:
        image: grafana/grafana:10.3.3
        depends_on:
            db:
                condition: service_healthy
        restart: always
        environment:
            - GF_SERVER_ROOT_URL=https://grafana.example.com/
        volumes:
            - grafana_storage:/var/lib/grafana
            - ./grafana.ini:/etc/grafana/grafana.ini:ro
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.grafana.entryPoints=https
            - traefik.http.routers.grafana.rule=Host(`grafana.example.com`)
            - traefik.http.routers.grafana.tls=true
            - traefik.http.routers.grafana.tls.certResolver=myResolver
            - traefik.http.services.grafana.loadBalancer.server.port=3000

    db:
        image: postgres:16.2
        restart: always
        healthcheck:
            test: pg_isready -d grafana
            interval: 5s
            timeout: 5s
            retries: 30
        environment:
            - POSTGRES_USER=grafana
            - POSTGRES_PASSWORD=${POSTGRES_GRAFANA_PASSWORD}
            - TZ=Europe/Moscow
        volumes:
            - postgres:/var/lib/postgresql/data:delegated

volumes:
    grafana_storage: null
    postgres: null

networks:
    traefik-public:
        external: true